#include "task.h"

const std::string taskName = "Task2";

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

uint fn(int n)
{
	return floor((pow(((1+sqrt(5.0))/2), n) - pow(((1-sqrt(5.0))/2), n))/sqrt(5.0) + 0.5);
}

// 33 Числа Фибоначчи до 4000000.
// Четные числа имеют номер 3*k.
int run()
{
	uint sum = 0;
	for(int i=3; i<=33; i=i+3) sum += fn(i);
	std::cout << std::endl << sum;
	return 0;
}